### ISSUE TITLE
ASP.NET Core: Not allowed methods on TableController return 500 Internal Server Error

### ISSUE THREAD

**Issue by cjaliaga** [Azure/azure-mobile-apps#102]
**Describe the bug**
Non-action methods in TableController appear as valid endpoints, causing an Internal Server Error when requesting non-valid endpoints like PUT on Listing.

```csharp
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 
BlogServer.Controllers.UsersController.IsAuthorized (BlogServer)
BlogServer.Controllers.UsersController.PrepareItemForStoreAsync (BlogServer)
BlogServer.Controllers.UsersController.PrepareItemForStore (BlogServer)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.Select(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
````

**Expected behavior**
The service should return a 405 (Method not allowed)

**What platforms?**
* Server:
    * [ ] ASP.NET Framework (Legacy)
    * [x] ASP.NET Core
    * [ ] Node.js (Legacy)

**Comment by adrianhall** [comment]
Fixed in 01e6c2f
