### ISSUE TITLE
CI Failure: Integration / Client / Delete

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#283]
CI Failure in `Microsoft.Datasync.Integration.Test.Client.DatasyncTable_Delete_Test.DeleteItemAsync_ConditionalFailure`

Error Message:
```
Date 12/10/2021 10:47:59 PM +00:00 and 12/10/2021 10:47:57 PM +00:00 are 2120.5351ms apart
Expected: True
Actual:   False
```

Stack trace:
```
   at Datasync.Common.Test.AssertEx.CloseTo(DateTimeOffset expected, DateTimeOffset actual, Int32 interval) in \sdk\dotnet\test\Datasync.Common.Test\AssertEx.cs:line 66
   at Datasync.Common.Test.AssertEx.SystemPropertiesSet(ITableData entity, Nullable`1 startTime) in \sdk\dotnet\test\Datasync.Common.Test\AssertEx.cs:line 128
   at Microsoft.Datasync.Integration.Test.Client.DatasyncTable_Delete_Test.DeleteItemAsync_ConditionalFailure() in \sdk\dotnet\test\Microsoft.Datasync.Integration.Test\Client\DatasyncTable.Delete.Test.cs:line 126
--- End of stack trace from previous location ---
```

**Comment by adrianhall** [comment]
PR #295 added stdout logging to all the integration tests.  In cases where the HTTP Status Code returned by the server is not expected, the test suite will now log the request and response, thus enabling us to attempt to provide an exact duplicate for the failure that can be run on a desktop for diagnosis.   However, in doing this, all the tests now pass on the first run.  

I'll open new bugs when those specific errors crop up.
