### ISSUE TITLE
Test Failure: Microsoft.Datasync.Integration.Test.Server.Patch_Tests.SoftDeletePatch_CanUndeleteDeletedItem(table: "soft_logged")

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#303]
Error Message:
```
Assert.NotEqual() Failure
Expected: Not [50, 48, 50, 50, 45, ...]
Actual:   [50, 48, 50, 50, 45, ...]
```

Stack trace
```
   at Datasync.Common.Test.AssertEx.SystemPropertiesChanged(ITableData original, ITableData replacement) in D:\a\_work\1\s\sdk\dotnet\test\Datasync.Common.Test\AssertEx.cs:line 138
   at Microsoft.Datasync.Integration.Test.Server.Patch_Tests.SoftDeletePatch_CanUndeleteDeletedItem(String table) in D:\a\_work\1\s\sdk\dotnet\test\Microsoft.Datasync.Integration.Test\Server\Patch.Test.cs:line 323
--- End of stack trace from previous location ---
```

Stdout:

```
Request: https://localhost/tables/soft_logged/id-213
```

**Comment by adrianhall** [comment]
This is a transient error due to in-memory SQLite problems.  Need more data to properly diagnose.  Added more info in #304, but this is "for now" not an issue.
