### ISSUE TITLE
Token refresh fails for B2C apps after authentication token has expired

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-mobile-apps#44]
Stumbled upon this while helping a customer on [StackOverflow](http://stackoverflow.com/a/41252799/2069).

**Repro steps**
1. Configure Easy Auth to work with an AAD B2C app as described here: https://cgillum.tech/2016/08/10/app-service-auth-and-azure-ad-b2c-part-2/
2. Use the mobile SDK to log in
3. Wait for the authentication (zumo) token to expire (60+ minutes) but wait no longer than 72 hours.
4. Refresh the token

**Expected**
Refresh succeeds if done within the 72 hour window.

**Actual**
Token refresh fails with an internal server error. If you look at the application logs, you'll see something like this:

```
2017-02-20T20:16:54  PID[6248] Critical    **System.ArgumentException: IDX10401: Expires: '02/19/2017 17:15:53' must be after NotBefore: '02/20/2017 20:16:54'**.
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.CreateToken(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, SigningCredentials signingCredentials, SignatureProvider signatureProvider)
   at Microsoft.Azure.AppService.Authentication.ModuleUtils.CreateSessionJwt(HttpRequestBase request, AuthenticatedUser user, Nullable`1 accessTokenExpiration)
   at Microsoft.Azure.AppService.Authentication.EasyAuthModule.SetSessionTokenResponse(HttpContextBase context, AuthenticatedUser user, TokenEntry userTokens)
   at Microsoft.Azure.AppService.Authentication.EasyAuthModule.<RefreshTokensAsync>d__4c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.AppService.Authentication.EasyAuthModule.<OnBeginRequestAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.AppService.Authentication.HttpModuleDispatcher.<DispatchAsync>d__13.MoveNext()

```
**Internal Details**
The root of the problem is that Easy Auth tries to calculate the expiration time for the refreshed authentication/zumo token using the expiration of the access token. If there is no access token, then it falls back to looking for an expiration claim for the current user principal.  This behavior is wrong, because the current user principal's session has already expired, so the code is trying to create a new session token that expires in the past.

**Workaround**
Token refresh still works if the session token used by the mobile SDK has not yet expired. However, this is not helpful for most customers since a larger interval of time is required for token refresh, like 72 hours. To create a better user experience in spite of this issue, it is recommended to increase the lifetime of the ID tokens in the B2C portal to a larger number, like 72 hours (or 4320 minutes).

**Comment by tomh4** [comment]
Anything new on this issue :)?

**Comment by cgillum** [comment]
Yes, the fix is nearly deployed everywhere. It should be available to all customers this weekend.

**Comment by tomh4** [comment]
Perfect!
Thank you:)

Am 17.03.2017 5:53 nachm. schrieb "Chris Gillum" <notifications@github.com>:

**Comment by cgillum** [comment]
The fix should be deployed everywhere. Let us know if you're still having problems.
