### ISSUE TITLE
Using an ITableQuery where clause with a LINQ expression containing a comparison to a negative value crashes

### ISSUE THREAD

**Issue by amertlich** [Azure/azure-mobile-apps#604]
## Describe the bug

An `ODataException` is being thrown here https://github.com/Azure/azure-mobile-apps/blob/71c07603cf87681e465df9fd150473c99e535785/sdk/dotnet/src/Microsoft.Datasync.Client/Query/OData/ODataExpressionParser.cs#L245 whenever a table query contains an expression like `query.Where(r => r.Value <= -0.5);`

with a table definition like
``` c#
public class Thing
{
    public string Id { get; set; }
    public double? Value { get; set; }
}
```
stack trace:
```
Microsoft.Datasync.Client.ODataException : Expression expected
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParsePrimary()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseUnary()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseUnary()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseMultiplicative()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseAdditive()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseComparison()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseLogicalAnd()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseLogicalOr()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseExpression()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseParenExpression()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParsePrimary()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseUnary()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseMultiplicative()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseAdditive()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseComparison()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseLogicalAnd()
   at Microsoft.Datasync.Client.Query.OData.ODataExpressionParser.ParseLogicalOr()
   at Microsoft.Datasync.Client.Query.QueryDescription.Parse(String tableName, String query)
   at Microsoft.Datasync.Client.Offline.SyncContext.GetNextPageAsync(String tableName, String query, CancellationToken cancellationToken)
   at Microsoft.Datasync.Client.Table.OfflineTable`1.GetNextPageAsync[U](ITableQuery`1 query, String nextLink, CancellationToken cancellationToken)
   at Microsoft.Datasync.Client.Table.FuncAsyncPageable`1.AsPages(String requestUri)+MoveNext()
   at Microsoft.Datasync.Client.Table.FuncAsyncPageable`1.AsPages(String requestUri)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.Datasync.Client.Table.AsyncPageable`1.GetAsyncEnumerator(CancellationToken token)+MoveNext()
   at Microsoft.Datasync.Client.Table.AsyncPageable`1.GetAsyncEnumerator(CancellationToken token)+MoveNext()
   at Microsoft.Datasync.Client.Table.AsyncPageable`1.GetAsyncEnumerator(CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.Datasync.Client.Extensions.LinqExtensions.ToZumoListAsync[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.Datasync.Client.Extensions.LinqExtensions.ToZumoListAsync[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
```

## To Reproduce

Get an `OfflineTable` instance from an initialized `DatasyncClient` and then query it with something like this:

 `query.Where(r => r.Value<= -0.5);`

## Expected behavior

The ODataExpressionParser shouldn't choke when the expression contains negative double arguments.

## What platforms?

Microsoft.Datasync.Client 5.0.21

**Comment by adrianhall** [comment]
May be the nullable that is the problem.

* Write test for double value comparison in TableQuery.Test.cs
* Figure out if it's a nullable issue or not.
* Write test for the nullable version
* Figure out the issue with the expression parser.

**Comment by adrianhall** [comment]
So, not an issue with the LINQ compiler.  These two tests work fine:

```csharp
        [Fact]
        public void ToODataString_NegativeDouble_Works()
        {
            var client = GetMockClient();
            var table = new RemoteTable<KSV>("ksv", client);
            var query = new TableQuery<KSV>(table).Where(x => x.Value <= -0.5) as TableQuery<KSV>;
            var actual = query.ToODataString();
            Assert.Equal("$filter=(value le -0.5)", actual);
        }

        [Fact]
        public void ToODataString_NegativeNullableDouble_Works()
        {
            var client = GetMockClient();
            var table = new RemoteTable<KSV>("ksv", client);
            var query = new TableQuery<KSV>(table).Where(x => x.NullableValue <= -0.5) as TableQuery<KSV>;
            var actual = query.ToODataString();
            Assert.Equal("$filter=(nullableValue le -0.5)", actual);
        }
```

Will leave them in.  Next suspect is the OData to SQL parser.

**Comment by adrianhall** [comment]
Reproduced the problem.  It's a round-trip to SQLite problem that is causing the issue.  Basically, you can't store a nullable primitive in SQLite - i.e. `double` works, but `double?` doesn't.  Will have to dig deeper on this one.

**Comment by adrianhall** [comment]
The error resulted in a pretty minor fix - thanks for reporting.  Will be in next release.

**Comment by amertlich** [comment]
Always amazed by your response time! Thanks!!
