### ISSUE TITLE
(release/6.0.0) Error in EFCore unit test

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps#636]
```text
##[error][xUnit.net 00:00:04.35]     Test.Datasync.EFCore.EntityTableRepository_Tests.ReplaceAsync_Replaces_OnNoVersion [FAIL]
[xUnit.net 00:00:04.36]       Assert.NotEqual() Failure
[xUnit.net 00:00:04.36]       Expected: Not "MjAyMy0wMi0yNyAwMDoxMzoyMS4wODE="
[xUnit.net 00:00:04.36]       Actual:   "MjAyMy0wMi0yNyAwMDoxMzoyMS4wODE="
[xUnit.net 00:00:04.36]       Stack Trace:
[xUnit.net 00:00:04.36]         D:\a\_work\1\s\sdk\dotnet\test\Test.Datasync.Common\Assertions\AssertEx.cs(67,0): at Test.Datasync.Common.Assertions.AssertEx.SystemPropertiesChanged(ITableData original, ITableData replacement)
[xUnit.net 00:00:04.36]         D:\a\_work\1\s\sdk\dotnet\test\server\Test.Datasync.EFCore\EntityTableRepository_Tests.cs(416,0): at Test.Datasync.EFCore.EntityTableRepository_Tests.ReplaceAsync_Replaces_OnNoVersion()
[xUnit.net 00:00:04.36]         --- End of stack trace from previous location ---
```

**Comment by adrianhall** [comment]
Fixed by adding a retryfact to the flaky test.
