### ISSUE TITLE
Clearing errors from the operations queue fails when rawResult is not JSON

### ISSUE THREAD

**Issue by amertlich** [Azure/azure-mobile-apps#797]
## Describe the bug

If the __errors table contains a row with a `rawResult` set to something that is not JSON it can cause the Offline SyncContext to fail to initialize.

## To Reproduce

Create an entry in the __errors table like this:
![image](https://github.com/Azure/azure-mobile-apps/assets/1198524/e749c1cc-07e7-4ef5-b01b-1bd0dedcfe31)

Try to initialize the Offline DataSyncClient

Alternatively when pushing an item and the server response with a non JSON result:
```
Status: CancelledByNetworkError
Microsoft.Datasync.Client.Offline.PushFailedException: Push operation has failed. See the PushResult for details.
 ---> System.AggregateException: One or more errors occurred. (Failed to read errors from the local store.)
 ---> Microsoft.Datasync.Client.Offline.OfflineStoreException: Failed to read errors from the local store.
 ---> Newtonsoft.Json.JsonSerializationException: Deserialized JSON type 'Newtonsoft.Json.Linq.JValue' is not compatible with expected type 'Newtonsoft.Json.Linq.JObject'. Path '', line 1, position 5.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Datasync.Client.Offline.Queue.TableOperationError.Deserialize(JObject obj, DatasyncSerializerSettings serializerSettings)
   at Microsoft.Datasync.Client.Offline.Queue.OperationBatch.<GetNextPageAsync>b__17_0(JObject err)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at Microsoft.Datasync.Client.Table.AsyncPageable`1.GetAsyncEnumerator(CancellationToken token)+MoveNext()
   at Microsoft.Datasync.Client.Table.AsyncPageable`1.GetAsyncEnumerator(CancellationToken token)+MoveNext()
   at Microsoft.Datasync.Client.Table.AsyncPageable`1.GetAsyncEnumerator(CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.Datasync.Client.Offline.Queue.OperationBatch.LoadErrorsAsync(CancellationToken cancellationToken)
   at Microsoft.Datasync.Client.Offline.Queue.OperationBatch.LoadErrorsAsync(CancellationToken cancellationToken)
   at Microsoft.Datasync.Client.Offline.SyncContext.PushItemsAsync(String[] tableNames, PushOptions options, CancellationToken cancellationToken)
```

## Expected behavior

Catch `JsonException` on Line 204 of TableOperationError.cs instead of the more concrete `JsonReaderException` since it may also be a `JsonSerializationException`
https://github.com/Azure/azure-mobile-apps/blob/main/sdk/dotnet/src/Microsoft.Datasync.Client/Offline/Queue/TableOperationError.cs#L204

## What platforms?

6.0.4 Client SDK

**Comment by adrianhall** [comment]
Not sure how this would actually happen.  Unless you are messing with the internals of the queue, the rawResult should either be not set / empty or valid JSON.  However, this is a harmless change, so I'll put it in.
