### ISSUE TITLE
Incremental sync has the potential to pull excessive amounts of data into memory due to client side result Count evaluation

### ISSUE THREAD

**Issue by amertlich** [Azure/azure-mobile-apps#818]
## Describe the bug

We noticed that when a client requests an incremental sync that requires a large amount of data (i.e. 100K+ records) that, at least with a Postgres Database, it will fallback to a client side evaluation of the record count [see here](https://github.com/Azure/azure-mobile-apps/blob/0bafb6c742602802188cb77f24885c97dde7b370/sdk/dotnet/src/Microsoft.AspNetCore.Datasync/Tables/TableController.cs#L398)

This has the potential to pull gigabytes of records into the app-service memory server side and causes load issues and bandwidth and scalability problems. We have other endpoints using entity framework directly to perform count queries that are succeeding with even larger data sets so not sure what the limitation is here or if it's just a timeout/query performance problem.

## To Reproduce

1. Use Postgres as the backend database
2. Attempt an pull/incremental sync of more than 200K objects
3. If Postgres throws an error around [here](https://github.com/Azure/azure-mobile-apps/blob/0bafb6c742602802188cb77f24885c97dde7b370/sdk/dotnet/src/Microsoft.AspNetCore.Datasync/Tables/TableController.cs#L390)
4. Then a fallback to client side evaluation is performed [here](https://github.com/Azure/azure-mobile-apps/blob/0bafb6c742602802188cb77f24885c97dde7b370/sdk/dotnet/src/Microsoft.AspNetCore.Datasync/Tables/TableController.cs#L394)
5. Which causes all 200K objects to be transferred from the DBContext into appservice memory

## Expected behavior

Should not pull hundreds of thousands of records into memory, especially if the exception was a TimeoutException.

## What platforms?

6.0.5 Client and Server

* Server:
  * Version of dotnet being used to compile? .NET 7.0
  * Library versions? 6.0.5
  * What database are you using? Postgres
  * Where are you running the server? Azure App SErvice

* Client:
6.0.4, Xamarin.Forms, WPF

## Additional context

Here's a stack trace of the exception thrown at the Postgress level that triggered the fallback:

```
fail: Microsoft.EntityFrameworkCore.Query[10100]
       An exception occurred while iterating over the results of a query for context type 'MyApp.Backend.Data.Context.MyAppDbContext'.
       System.InvalidOperationException: An exception has been raised that is likely due to a transient failure.
        ---> Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
        ---> System.TimeoutException: Timeout during reading attempt
          at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
          at Npgsql.NpgsqlDataReader.NextResult()
          at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
          at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
          at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
          at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
          --- End of inner exception stack trace ---
          at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
       System.InvalidOperationException: An exception has been raised that is likely due to a transient failure.
        ---> Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
        ---> System.TimeoutException: Timeout during reading attempt
          at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
          at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
          at Npgsql.NpgsqlDataReader.NextResult()
          at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
          at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
          at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
          at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.<>c.<MoveNext>b__21_0(DbContext _, Enumerator enumerator)
          at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
          --- End of inner exception stack trace ---
          at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
          at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
 warn: MyApp.Backend.Controllers.DataSyncTables.RecordsController[0]
       Error while executing query for long count: Possible client-side evaluation (Exception while reading from stream)
```

**Comment by adrianhall** [comment]
This is expected if you are doing a client-side evaluation.  It has nothing to do with us (and hence we can't do anything about it).  It has to do with indexing and what query you are actually sending to the server. 

Note that when a TimeoutException occurs, that bubbles up properly.  Only the "NotSupportedException" and "InvalidOperationException" are actually considered "client-side evaluation problems" which we then switch over to client-side evaluation.

We could refuse to process client-side evaluations - that, however, would cause your application to crash.

To further diagnose, I'd need to know:

* What does your model look like?
* What does the SQL table definition look like?
* What query are you sending to the server?
* Have you indexed all the fields involved in the query?

You may need to add an explicit index on UpdatedAt and Deleted fields.

**Comment by amertlich** [comment]
I think the problem is that the inner, inner exception is actually a timeout exception that gets wrapped as an InvalidOperationException. So it seems InvalidOperationExceptions can't be relied on to assume the provider doesn't support the functionality. In this case it does support it, but the query just timed out, so falling back to client eval seems just as likely (if not more likely) to fail for performance reasons.

But you're right, the lack of indexes are likely causing the poor query performance. We've added some indexes and noticed some improvement there, but this is still possible in scenarios where we're under load and queries timeout for other reasons.

 I still think the client-side evaluation fallback is worse than failing 1 particular client request. The fallback has the potential to crash and restart the entire app service effecting all clients or at least consume way more resources that will effect all clients and not just the single request.

To answer your questions:

**What does your model look like?** Our model has about 19 columns, 1 column represents a JSON document that can be up to 500kb
**What does the SQL table definition look like?**  essentially the same as the model
**What query are you sending to the server?** We're invoking IOfflineTable `PullItemsAsync` on the mobile client side and only specifying a QueryId in the PullOptions without any other parameters. (Essentially pulling down the entire table for a particular user). The backend TableController enforces some authorization and modifies the QueryString to filter to the authenticated user's data before invoking base.QueryAsync
**Have you indexed all the fields involved in the query?** We've added an additional index for UpdatedAt and Deleted as well as an index for the column we use to filter user data and this has improved query performance, but still worry this client fallback code can still happen and take down the server.

**Comment by adrianhall** [comment]
Got it - what I will do is add a table controller option to disable client-side evaluation.  This will cause any of these sorts of queries to return a 500 Internal Server Error, which will bubble back to the client rather quickly.

**Comment by amertlich** [comment]
That should work. 

Alternatively (which admittedly would take more work/change) you could make sure the fallback query, that only appears to be used for a total result count, just select on the ID column so that you [avoid the ToList()](https://github.com/Azure/azure-mobile-apps/blob/0bafb6c742602802188cb77f24885c97dde7b370/sdk/dotnet/src/Microsoft.AspNetCore.Datasync/Tables/TableController.cs#L398) call on the dataset that hasn't yet been paged/skipped.  Basically only enumerate to a list that only will select IDs rather than the entire row to get the total results count and then you'll avoid enumerating the full dataset. But possibly I'm not understanding how the PagedResult is working completely.

**Comment by adrianhall** [comment]
Client side evaluation is done for both the actual entities and the total count, so disabling one and not the other is not reasonable.
