### ISSUE TITLE
InvalidOperationException at DatasyncContractResolver.CreateProperties

### ISSUE THREAD

**Issue by asierpn** [Azure/azure-mobile-apps#868]
## Describe the bug

Often the DatasyncClient throws an InvalidOperationException at the DatasyncContractResolver.CreateProperties method when performing a query, but the error is temporary because when I retry the operation it works fine. It appears that the jsonPropertyCache has not yet been initialised.

```
Message: Sequence contains no matching element
Stacktrace:    at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Microsoft.Datasync.Client.Serialization.DatasyncContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Microsoft.Datasync.Client.Query.Linq.QueryTranslator`1.AddProjection(MethodCallExpression expression)
   at Microsoft.Datasync.Client.Query.Linq.QueryTranslator`1.VisitMethodCall(MethodCallExpression expression)
   at Microsoft.Datasync.Client.Query.Linq.QueryTranslator`1.VisitMethodCall(MethodCallExpression expression)
   at Microsoft.Datasync.Client.Query.Linq.QueryTranslator`1.Translate()
   at Microsoft.Datasync.Client.Query.TableQuery`1.ToODataString(Boolean includeParameters)
   at Microsoft.Datasync.Client.Table.OfflineTable`1.GetNextPageAsync[U](ITableQuery`1 query, String nextLink, CancellationToken cancellationToken)
   at Microsoft.Datasync.Client.Table.FuncAsyncPageable`1.AsPages(String requestUri)+MoveNext()
   at Microsoft.Datasync.Client.Table.FuncAsyncPageable`1.AsPages(String requestUri)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.Datasync.Client.Table.AsyncPageable`1.GetAsyncEnumerator(CancellationToken token)+MoveNext()
   at Microsoft.Datasync.Client.Table.AsyncPageable`1.GetAsyncEnumerator(CancellationToken token)+MoveNext()
   at Microsoft.Datasync.Client.Table.AsyncPageable`1.GetAsyncEnumerator(CancellationToken token)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.Datasync.Client.Extensions.LinqExtensions.ToZumoListAsync[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.Datasync.Client.Extensions.LinqExtensions.ToZumoListAsync[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
```

## To Reproduce

1. Do several queries concurrently against different entities

## Expected behavior

No exception occurs in DatasyncContractResolver.CreateProperties.

## What platforms?

* Client:
  * Version of dotnet being used to compile? NET8
  * .NET Runtime Environment (WPF, UWP, Xamarin.Forms, etc.): WinAppSDK 1.4.3
  * Library versions? 6.0.7
  * What platform versions are you running on? Windows 10
  * Does it happen in an emulator / simulator, or only on a real device? Real device

## Additional context

I'm considering using a retry policy for this type of exception when calling a DatasyncClient's method, but this is not elegant.

**Comment by asierpn** [comment]
I remember I had the same issue with the previous client implementation (4.2.0) and I had to do a fork to modify the MobileServiceContractResolver. This issue still exists in the current client and the solution is the same, modifying this line solves the issue:

`var memberInfo = relevantProperties.Single(x => x.Value.PropertyName == property.PropertyName).Key;`

I don't know why this happens, but sometimes the JsonProperty contained in the cache is not the same instance as the one returned by the base.CreateProperties method, I created a ticket for this issue in the previous repository, but I think that it has been lost.

In my fork of the previous client implementation I had to add another condition to this line to avoid an issue when a derived type overrides a base property using the "new" keyword:

`var memberInfo = relevantProperties.Single(x => x.Value.PropertyName == property.PropertyName && x.Value.DeclaringType == property.DeclaringType).Key;`

Can you fix this issue? If not, at least an easy way to replace the current DatasyncContractResolver without forking the project would be helpful.

**Comment by adrianhall** [comment]
Should be a relatively easy fix.  I'll get it in before I cut the release tomorrow.
