### ISSUE TITLE
System.InvalidOperationException when Id is set on client when calling RemoteTable.InsertItemAsync

### ISSUE THREAD

**Issue by richard-einfinity** [Azure/azure-mobile-apps#902]
## Describe the bug

When the entity id is set on the client the server returns 

System.InvalidOperationException: The LINQ expression 'DbSet<EntityType>()
    .Any(i => i.Id == __entity_Id_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.

## To Reproduce

1). Setup the api and client for a remote table.
2). Set the id to a value on the client side.
3). Call RemoteTable.InsertItemAsync

## Expected behavior

Check if the entity exists. If so throw a conflict exception. If not insert the entity.

## What platforms?

> **Note**: Any bug or feature request that is opened for an unsupported environment will be automatically closed.

* Server:
  * Version of dotnet being used to compile? .Net 8.0
  * Library versions? 6.10
  * What database are you using? Cosmos DB
  * Where are you running the server? Kestral and Azure

* Client:
  * Version of dotnet being used to compile? Net 8.0
  * .NET Runtime Environment (WPF, UWP, Xamarin.Forms, etc.): Maui
  * Library versions? 6.10
  * What platform versions are you running on? Android / iOS
  * Does it happen in an emulator / simulator, or only on a real device? Both

## Additional context

Seems as though the issue occurs here https://github.com/Azure/azure-mobile-apps/blob/a7418211710416c542c41e81a9ccdf955a47d4b1/sdk/dotnet/src/Microsoft.AspNetCore.Datasync.EFCore/EntityTableRepository.cs#L106 

Doesn't like the Any expression. Changing to Count > 0 restores the desired functionality. 

Happy to submit PR

**Comment by adrianhall** [comment]
I will have to dive into this, especially considering the re-write of the EntityTableRepository in v8.

**Comment by adrianhall** [comment]
Do you have a simple repro of what you are doing to cause the issue?

**Comment by richard-einfinity** [comment]
Hi Adrian,

I'm just setting the entity id on the client side before calling RemoteTable.InsertItemAsync, which I think would break offline sync as well?

I haven't got a repro of what I'm doing at the moment I can share, I'll see if I can reproduce using your templates and share what I find. I have worked around the issue by overloading the CreateAsync method on the EntityTableRepository. Code below:

`public override async Task CreateAsync(TModel entity, CancellationToken token = default)
{
    if (entity == null)
    {
        throw new ArgumentNullException(nameof(entity));
    }

    try
    {
        string id = entity.Id;
        if (id != null && _dataset.Count(x => x.Id == id) > 0)
        {
            throw new ConflictException(await GetEntityAsync(entity.Id, token).ConfigureAwait(false));
        }
        entity.Id ??= Guid.NewGuid().ToString("N");
        entity.UpdatedAt = DateTimeOffset.UtcNow;
        _dataset.Add(entity);
        await _context.SaveChangesAsync(token).ConfigureAwait(false);
    }
    catch (DbUpdateException ex)
    {
        throw new RepositoryException(ex.Message, ex);
    }
}`

**Comment by adrianhall** [comment]
Ack - feels like a limitation in the Cosmos implementation of EFCore.  Since there is a performance penalty on our P0 requirement (support for SQL), I'll have to figure out a nice way to handle this for Cosmos.

**Comment by richard-einfinity** [comment]
Hi Adrian,

I pulled the samples, configured and run the cosmosdb api.

`curl -X 'POST' \
  'https://localhost:7048/tables/todoitem' \
  -H 'accept: application/json' \
  -H 'ZUMO-API-VERSION: 3.0.0' \
  -H 'Content-Type: application/json' \
  -d '{
  "id": "E1084508-3D58-4660-957F-1EEDAEB0FA36",
  "title": "Check comsmos add",
  "isComplete": true
}'
`

Result

`System.InvalidOperationException: The LINQ expression 'DbSet<TodoItem>()
    .Any(t => t.Id == __entity_Id_0)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0&)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Cosmos.Query.Internal.CosmosQueryableMethodTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.AspNetCore.Datasync.EFCore.EntityTableRepository`1.CreateAsync(TEntity entity, CancellationToken token)
   at Microsoft.AspNetCore.Datasync.TableController`1.CreateAsync(TEntity item, CancellationToken token) in C:\Users\Richard\Source\Repos\azure-mobile-apps\sdk\dotnet\src\Microsoft.AspNetCore.Datasync\Tables\TableController.cs:line 239
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResourceFilter()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json
Host: localhost:7048
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9,en-US;q=0.8
Content-Type: application/json
Cookie: ai_user=GcsXsDZPz4TX8FUFtxAzDK|2023-06-15T20:51:59.642Z; ai_session=a202WnjtBSy17oQzhxRM2q|1709667175203|1709667175213
Origin: https://localhost:7048
Referer: https://localhost:7048/swagger/index.html
Content-Length: 104
sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Microsoft Edge";v="122"
zumo-api-version: 3.0.0
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty`

I think your right, when I was looking last night at the cosmos dB linq implementation. I don't think it implements all the functions. 

https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/linq-to-sql

Hope this helps.
